# Generated by Django 2.2.7 on 2020-04-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.TextField(default='null'),
        ),
    ]
