# Generated by Django 2.2.7 on 2020-04-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200406_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='frontPic',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
