# Generated by Django 2.2.7 on 2020-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=models.TextField(default='null'),
        ),
    ]
