# Generated by Django 2.2.7 on 2020-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200513_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videofile1',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile10',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile11',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile12',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile13',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile14',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile15',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile16',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile17',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile18',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile19',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile2',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile20',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile21',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile22',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile23',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile24',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile25',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile26',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile27',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile28',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile29',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile3',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile30',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile4',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile5',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile6',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile7',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile8',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='videofile9',
            field=models.FileField(default='null', null=True, upload_to='courses/videos/'),
        ),
    ]
