# Generated by Django 2.0.2 on 2020-06-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200515_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='about',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='frontPic',
            new_name='FrontPic',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='tags',
            new_name='Tags',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='frontPic_fileName',
        ),
    ]
