# Generated by Django 2.0.2 on 2020-07-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200601_0625'),
        ('courses', '0010_auto_20200601_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
    ]
