# Generated by Django 2.0.2 on 2021-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200901_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.TextField(default='null')),
                ('Email', models.EmailField(max_length=70)),
                ('Phone', models.BigIntegerField(default=9898989898)),
                ('CourseId', models.IntegerField(default=0)),
                ('CourseName', models.CharField(default='null', max_length=50)),
                ('Confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
