# Generated by Django 2.0.2 on 2021-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courseapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Display',
            field=models.BooleanField(default=False),
        ),
    ]
