# Generated by Django 2.0.2 on 2021-02-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='Position',
            field=models.IntegerField(default=1),
        ),
    ]
