# Generated by Django 2.0.2 on 2020-08-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=70)),
                ('Phone', models.BigIntegerField(default=9898989898)),
                ('CorpName', models.CharField(default='null', max_length=100)),
                ('Position', models.CharField(default='null', max_length=100)),
                ('Subject', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTrainingApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=70)),
                ('Phone', models.BigIntegerField(default=9898989898)),
                ('CourseId', models.IntegerField(default=0)),
                ('Confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About', models.TextField(default='null')),
                ('Price', models.IntegerField(default=0)),
                ('FrontPic', models.ImageField(default='null', upload_to='TrainingPrograms/FrontPics/')),
                ('Tags', models.TextField(default='null')),
                ('Display', models.BooleanField(default=False)),
                ('Address', models.TextField(default='Leader Factory, Mumbai')),
                ('Dates', models.TextField(default='null')),
                ('FrontPic_FileName', models.CharField(default='ForDeveloper', max_length=50)),
            ],
        ),
    ]
