# Generated by Django 2.0.2 on 2020-08-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetraining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetrainingprogram',
            name='FrontPic_FileName',
        ),
        migrations.AlterField(
            model_name='onlinetrainingprogram',
            name='FrontPic',
            field=models.ImageField(default='null', upload_to='OnlineTrainingPrograms/FrontPics/'),
        ),
    ]
