# Generated by Django 2.2.7 on 2020-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('pw', models.TextField(max_length=200)),
                ('phone', models.IntegerField(default=9898989898)),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
    ]
