# Generated by Django 2.2.7 on 2020-04-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='pw',
            field=models.TextField(max_length=50),
        ),
    ]
