# Generated by Django 2.2.7 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200406_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pw',
            field=models.CharField(max_length=50),
        ),
    ]
