# Generated by Django 2.2.7 on 2020-04-06 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videofile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, upload_to='videos/'), null=True, size=30),
        ),
    ]
