# Generated by Django 2.2.7 on 2020-04-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200406_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
