# Generated by Django 2.0.2 on 2020-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200515_1712'),
        ('user', '0008_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='courses',
            field=models.ManyToManyField(to='courses.courses'),
        ),
    ]
