# Generated by Django 2.0.2 on 2020-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_users_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='courses',
            new_name='Courses',
        ),
    ]
