# Generated by Django 2.0.2 on 2020-06-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200531_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='premium',
            new_name='Premium',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='pw',
            new_name='Pw',
        ),
    ]
