# Generated by Django 2.0.2 on 2020-07-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200717_1655'),
        ('user', '0011_auto_20200601_0625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
