# Generated by Django 2.0.2 on 2020-07-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200717_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Pw',
            new_name='Password',
        ),
    ]
