# Generated by Django 2.0.2 on 2020-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200717_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeFeaturedPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.FileField(default='null', upload_to='')),
                ('URLPointer', models.TextField(default='null')),
            ],
        ),
    ]
