# Generated by Django 2.0.2 on 2021-01-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_threefeaturedpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='threefeaturedpic',
            name='Position',
            field=models.IntegerField(default=1),
        ),
    ]
