# Generated by Django 2.0.2 on 2021-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_threefeaturedpic_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.TextField(default='null'),
        ),
    ]
