# Generated by Django 2.0.2 on 2020-09-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audresource',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='jpgresource',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='otherresource',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='pdfresource',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='pptresource',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='vidresource',
            name='Tags',
        ),
    ]
