# Generated by Django 2.2.7 on 2020-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About', models.TextField(default='null')),
                ('Price', models.IntegerField(default=0)),
                ('FrontPic', models.ImageField(default='null', upload_to='courses/frontpics/')),
                ('Tags', models.TextField(default='null')),
                ('Display', models.BooleanField(default=False)),
                ('Dates', models.DateField(default='2000-07-08')),
                ('FrontPic_FileName', models.CharField(default='ForDeveloper', max_length=50)),
            ],
        ),
    ]
