# Generated by Django 2.2.7 on 2020-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprograms',
            name='Dates',
            field=models.TextField(default='null'),
        ),
    ]
