# Generated by Django 2.2.7 on 2020-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200515_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprograms',
            name='Address',
            field=models.TextField(default='Leader Factory, Mumbai'),
        ),
        migrations.AlterField(
            model_name='trainingprograms',
            name='FrontPic',
            field=models.ImageField(default='null', upload_to='TrainingPrograms/FrontPics/'),
        ),
    ]
