# Generated by Django 2.2.7 on 2020-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200516_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.BigIntegerField(default=9898989898)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
