# Generated by Django 2.2.7 on 2020-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingapplicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingapplicants',
            old_name='confirmed',
            new_name='Confirmed',
        ),
        migrations.RenameField(
            model_name='trainingapplicants',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='trainingapplicants',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='trainingapplicants',
            name='Course',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
