# Generated by Django 2.0.2 on 2020-07-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20200602_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingApplicants',
            new_name='TrainingApplicant',
        ),
        migrations.RenameModel(
            old_name='TrainingPrograms',
            new_name='TrainingProgram',
        ),
    ]
