# Generated by Django 2.0.2 on 2020-08-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20200719_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='FrontPic_FileName',
        ),
    ]
