# Generated by Django 2.0.2 on 2020-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_trainingprogram_frontpic_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='Category',
            field=models.CharField(choices=[('1', 'Insurance'), ('2', 'Sales'), ('3', 'Network Marketing'), ('4', 'Business'), ('5', 'Self Development')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='Dates',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
