# Generated by Django 2.0.2 on 2020-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20200825_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApplicantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.TextField(default='null')),
            ],
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='Language',
            field=models.CharField(default='Hindi', max_length=50),
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='Category',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='ApplicantType',
            field=models.ManyToManyField(to='training.TrainingApplicantType'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='Category',
            field=models.ManyToManyField(to='training.TrainingCategory'),
        ),
    ]
