# Generated by Django 2.0.2 on 2021-01-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20200826_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='Position',
            field=models.IntegerField(default=1),
        ),
    ]
