# Generated by Django 2.0.2 on 2021-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_trainingprogram_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplicant',
            name='Address',
            field=models.TextField(default='null'),
        ),
    ]
