# Generated by Django 2.2.7 on 2020-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About', models.TextField(default='null')),
                ('Price', models.IntegerField(default=0)),
                ('FrontPic', models.ImageField(default='null', upload_to='Products/FrontPics/')),
                ('Tags', models.TextField(default='null')),
            ],
        ),
    ]
