# Generated by Django 2.0.2 on 2020-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.TextField(default='null')),
                ('Phone', models.BigIntegerField(default=9898989898)),
                ('Email', models.EmailField(default='null', max_length=254)),
                ('ProductId', models.IntegerField(default=0)),
                ('ProductName', models.CharField(max_length=100)),
            ],
        ),
    ]
