# Generated by Django 2.0.2 on 2020-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brief',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
