# Generated by Django 2.0.2 on 2020-07-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200725_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
    ]
