# Generated by Django 2.0.2 on 2020-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200930_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DaysForDelivery',
            field=models.IntegerField(default=8),
        ),
    ]
