# Generated by Django 2.0.2 on 2021-04-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_daysfordelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Dealer',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ShowDealer',
            field=models.BooleanField(default=False),
        ),
    ]
